name: AWS EC2 Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
    workflow-dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Login to SSH
        uses: appleboy/ssh-action@master
        env:
            TOKEN: ${{ secrets.TOKEN }}}
        with:
          host: ${{ secrets.host}}
          username: ${{ secrets.username}}
          key: ${{ secrets.key}}
          script: |
            rm -rf 1337x-bot
            git clone git@github.com:brandongallagher1999/1337x-bot.git
            cd 1337x-bot
            sudo docker-compose build --build-arg TOKEN=${{ secrets.TOKEN }}
            sudo docker-compose up -d