name: Azure Deployment

on: workflow_dispatch

jobs:
  build:
    name: Build Docker Image and deploy to Azure Linux VM
    runs-on: ubuntu-latest
    steps:
      - name: Login to SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host}}
          username: ${{ secrets.username}}
          key: ${{ secrets.key}}
          script: |
            sudo docker kill $(sudo docker ps -q)
            yes | sudo docker system prune -a
            rm -rf 1337x-bot
            git clone git@github.com:brandongallagher1999/1337x-bot.git
            cd 1337x-bot
            echo { '"token"' : '"'${{ secrets.token }}'"' } > config.json
            sudo docker-compose up -d