name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5

      - name: Install npm packages
        run: npm ci
      - name: Compile TypeScript Files
        run: npm run compile
      - name: Test Files
        run: npm test
