name: CI

on:

  push:
    branches: [ master, pre-prod ]
  pull_request:
    branches: [ master, pre-prod ]


  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5

      - name: Install npm packages
        run: npm ci
      - name: Compile TypeScript Files
        run: npm run compile
        #Running tests isn't working with Cloudflare for now. I am going to leave it out indefintiely.
      - name: Run tests
        run: npm test
