name: Build & Test

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "17"
      - name: Install npm packages
        run: yarn install
      - name: Compile TypeScript Files
        run: yarn run compile
      - name: Run tests
        run: yarn test
