name: Build & Test

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [branch]

      - name: Build Dockerfile
        run: docker-compose build

      - name: Run tests via Docker
        run: docker-compose run bot test
