name: Tag, Release & Deploy

on:
  push:
    branches: [master]
  
  workflow_dispatch:

jobs:
  release:
    name: Tag & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [master]
        with:
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config user.name = "GitHub Actions Bot"
          git config user.email = "<>"

      - name: Create new Tag
        run: git tag -a ${{ github.run_number }} -m "Release v${{ github.run_number}}"

      - name: Push Tag
        run: git push --tags

      - name: Create and Publish Release
        run: gh release create ${{ github.run_number }} --generate-notes -t "Release v${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Build Docker Image and deploy to Azure Linux VM
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Login to SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          script: |
            sudo docker kill $(sudo docker ps -q)
            yes | sudo docker system prune -a
            rm -rf 1337x-bot
            git clone git@github.com:brandongallagher1999/1337x-bot.git
            cd 1337x-bot
            echo { '"token"' : '"'${{ secrets.token }}'"' } > config.json
            sudo docker-compose up -d
